### ISSUE TITLE
Is there a way to use the NewRelicFormatter with the sink?

### ISSUE THREAD

**Issue by kiriasCMNH** [stanisls/serilog-sinks-newreliclogs#3]
I was checking the code in the actual implementation of the sink, and it can receive an optional IFormatProvider, but when instantiating it there is no option to pass the format provider to the extension method.

**Comment by stanisls** [comment]
Not as it is. I will create a PR with this option to https://github.com/thiagobarradas/serilog-sinks-newrelic-logs, which a fork supporting both .NET Framework 4.6.1 and .NET Core 3.1 and maintained by @ThiagoBarradas

**Comment by stanisls** [comment]
Pushed final code update and published nuget package v1.2.2
